### ISSUE TITLE
you can help me ?

### ISSUE THREAD

**Issue by newerit** [mmitch/debian-live-mitch-zfs#1]
this is my first build debian iso

im trying 

clone this repo
install the live-build package
run make build as root
cp or dd the resulting live-image-amd64.hybrid.iso to a USB flash drive or burn it to a DVD
(Or, if you're me and have exactly my memory stick, run make write. Have a look at write-to-stick to change USB devices targeted by make write.)

but my directory is empyt
no iso file

**Comment by mmitch** [comment]
I can try - could you copy your terminal output here? (both the commands you entered and the resulting output)

**Comment by mmitch** [comment]
Closed because of missing feedback.
